# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('news_article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('original_article_link', models.URLField(max_length=500)),
                ('picture_link', models.URLField(max_length=500)),
                ('text', models.TextField()),
                ('short_summary', models.TextField()),
                ('medium_summary', models.TextField()),
                ('long_summary', models.TextField()),
            ],
        ),
    ]
