# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-28 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_summarizer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='publisher',
            new_name='organization',
        ),
    ]
