# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-28 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_summarizer_app', '0002_auto_20171128_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='picture_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
