# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_summarizer_app', '0003_auto_20171128_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='long_summary',
            new_name='long_top_summary',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='medium_summary',
            new_name='medium_top_summary',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='long_block_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='medium_block_summary',
            field=models.TextField(null=True),
        ),
    ]
