# This is a simple example Ansible playbook
---
- name: Starting a Simple Django App
  hosts: all
  remote_user: root
  become: true
  become_method: sudo
  environment: 
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  vars:
      repository_url: https://github.com/CornellNLP/CS4300.git
      repository_path: /home/vagrant/CS4300
  tasks:
    - name: Install necessary packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - libatlas-base-dev 
        - gfortran 
        - g++
        - build-essential
        - libssl-dev 
        - libffi-dev 
        - python-dev
        - postgresql
        - libpq-dev
        - git
        - python-pip
        - nginx
        - python-numpy
        - python-scipy
    - name: Run echo
      command: locale -a
    - name: Check if directory exists
      stat: path='{{ repository_path }}'
      register: cloned
    - name: Pull application repo
      command: chdir='{{ repository_path }}' git pull origin master
      when: cloned.stat.exists
    - name: Clone application repo
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'
      when: cloned.stat.exists == false
    - name: Install pip requirements
      pip: requirements='{{ repository_path }}/requirements.txt'
    - name: Copy Upstart configuration
      template: src=upstart.conf.j2 dest=/etc/init/upstart.conf
    - name: Make sure our server is running
      service: name=upstart state=started
    - name: Copy Nginx site values
      template: src=cs.nginx.j2 dest=/etc/nginx/sites-enabled/cs
      notify:
        - restart nginx
    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx
    - name: Make sure nginx is running
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted